---
targets:
  $default:
    sources:
      - lib/**
      # Note that it is important to include these in the default target.
      - pubspec.*
      - $package$
    builders:
      json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          - lib/app/service/*.dart
          - lib/app/service/**/*.dart
          - lib/data/*.dart
          - lib/data/**/*.dart
          - lib/http/*.dart
          - lib/http/**/*.dart
          - lib/feature/**/data/*.dart
          - lib/feature/**/data/**/*.dart
      retrofit_generator:
        generate_for:
          - lib/http/*.dart
          - lib/http/**/*.dart
          - lib/feature/**/data/*.dart
          - lib/feature/**/data/**/*.dart
      injectable_generator:injectable_builder:
        generate_for:
          - lib/core/*.dart
          - lib/di/*.dart
          - lib/di/**/*.dart
          - lib/app/service/*.dart
          - lib/app/service/**/*.dart
          - lib/http/*.dart
          - lib/bootstrap/*.dart
          - lib/http/**/*.dart
          - lib/feature/**/*_wm.dart
          - lib/feature/**/*_model.dart
          - lib/app/**/*_wm.dart
          - lib/app/**/*_model.dart
          - lib/widgets/**/*_wm.dart
          - lib/widgets/**/*_model.dart
          - lib/feature/**/domain/*.dart
          - lib/feature/**/domain/*.dart
          - lib/feature/**/domain/**/*.dart
          - lib/feature/**/*route.dart
          - lib/feature/**/*guard.dart
          - lib/app/router/router.dart
          - lib/app/router/guard.dart
          - lib/v1/**/*route.dart
          - lib/v1/**/*guard.dart
          - lib/utils/factories/error_handler/standard_error_handler.dart
      freezed:
        generate_for:
          - lib/app/service/*.dart
          - lib/app/service/**/*.dart
          - lib/data/*.dart
          - lib/data/**/*.dart
          - lib/*_state.dart
          - lib/**/*_state.dart
          - lib/feature/**/data/*.dart
          - lib/feature/**/data/**/*.dart
          - lib/feature/**/widget/**/*.dart
          - lib/feature/**/*route.dart
          - lib/v1/**/*route.dart
