---
name: wm_state_properties_lint
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  analyzer: ^7.6.0
  analyzer_plugin: ^0.13.0
  custom_lint_builder: ^0.8.0
  # path: ^1.8.0

dev_dependencies:
  injectable_generator: ^2.8.1
  lints: ^6.0.0
  test: ^1.24.0
